import { SoundManager } from "../../game/asset-manager/sound-manager.js";
import { SpriteManager } from "../../game/asset-manager/sprite-manager.js";
import { RendererEngine } from "../../game/renderer/renderer-engine.js";
import { TextManager } from "../../game/text/text-manager.js";
import { VisibilityManager } from "../../game/visibility/visibility-manager.js";
import { CameraManager } from "../../game/world/camera-manager.js";
import { PathFindingManager } from "../../game/world/pathfinding-manager.js";
import { WorldTilemapManager } from "../../game/world/world-tilemap-manager.js";
import { AIAttackOrderComponent } from "../components/ai-attack-order.component.js";
import { AiAttackRangeComponent } from "../components/ai-attack-range.component.js";
import { AIMovementOrderComponent } from "../components/ai-movement-order.component.js";
import { AiMovementRadiusComponent } from "../components/ai-movement-radius.component.js";
import { AIComponent } from "../components/ai.component.js";
import { AimRotationShootingComponent } from "../components/aim-rotation-shooting.component.js";
import { AnimTimerComponent } from "../components/anim-timer.component.js";
import { AnimationComponent } from "../components/animation.component.js";
import { AttackSpeedComponent } from "../components/attack-speed.component.js";
import { AwaitingAnimationEndComponent } from "../components/awaiting-animation-end.component.js";
import { BitmapTextComponent } from "../components/bitmap-text.component.js";
import { BloodParticlesComponent } from "../components/blood-particles.component.js";
import { BulletFiredComponent } from "../components/bullet-fired.component.js";
import { CameraComponent } from "../components/camera-component.js";
import { CollisionBoxComponent } from "../components/collision-box-component.js";
import { DamageDealtComponent } from "../components/damage-dealt.component.js";
import { DamageTakenIntentComponent } from "../components/damage-taken-intent.component.js";
import { DeathIntentComponent } from "../components/death-intent.component.js";
import { DelayedDestructionComponent } from "../components/delayed-destruction.component.js";
import { DialogAnimComponent } from "../components/dialog-anim.component.js";
import { DialogBubbleSpriteComponent } from "../components/dialog-bubble-sprite.component.js";
import { DialogIntentComponent } from "../components/dialog-intent.component.js";
import { DialogLifetimeComponent } from "../components/dialog-lifetime.component.js";
import { DialogComponent } from "../components/dialog.component.js";
import { DirectionAnimComponent } from "../components/direction-anim.component.js";
import { DirectionComponent } from "../components/direction-component.js";
import { DisableAimComponent } from "../components/disable-aim.component.js";
import { DisableAttachmentComponent } from "../components/disable-attachment.component.js";
import { DustParticlesComponent } from "../components/dust-particles.component.js";
import { EnemiesKilledComponent } from "../components/enemies-killed.component.js";
import { EnemyDeadComponent } from "../components/enemy-dead.component.js";
import { EnemyComponent } from "../components/enemy.component.js";
import { FuseTimerComponent } from "../components/fuse-timer.component.js";
import { GrenadeComponent } from "../components/grenade-component.js";
import { GrenadeCooldownComponent } from "../components/grenade-cooldown.component.js";
import { GrenadeExplosionComponent } from "../components/grenade-explosion.component.js";
import { GrenadeFiredComponent } from "../components/grenade-fired.component.js";
import { HealthComponent } from "../components/health.component.js";
import { HitBoxComponent } from "../components/hit-box-component.js";
import { InitialAimAngleComponent } from "../components/initial-aim-angle.component.js";
import { IntentClickComponent } from "../components/intent-click.component.js";
import { IntentGrenadeComponent } from "../components/intent-grenade.component.js";
import { IntentMeleeComponent } from "../components/intent-melee.component.js";
import { IntentShotComponent } from "../components/intent-shot.component.js";
import { InventoryComponent } from "../components/inventory-component.js";
import { ItemBoxComponent } from "../components/item-box.component.js";
import { ItemDropIntentComponent } from "../components/item-drop-intent.component.js";
import { ItemDroppedComponent } from "../components/item-dropped.component.js";
import { MeleeIntentProcessedComponent } from "../components/melee-intent-processed.component.js";
import { MovementIntentComponent } from "../components/movement-intent.component.js";
import { OffsetAppliedComponent } from "../components/offset-applied.component.js";
import { PlayerComponent } from "../components/player.component.js";
import { PositionComponent } from "../components/position.component.js";
import { ProjectileComponent } from "../components/projectile-component.js";
import { ReloadIntentComponent } from "../components/reload-intent.component.js";
import { RenderableComponent } from "../components/renderable-component.js";
import { ScreenPositionComponent } from "../components/screen-position.component.js";
import { ShapeAngleComponent } from "../components/shape-angle.component.js";
import { ShapeComponent } from "../components/shape-component.js";
import { ShapeDimensionComponent } from "../components/shape-dimension.component.js";
import { ShapeDirectionComponent } from "../components/shape-direction.component.js";
import { ShapeHitMemoryComponent } from "../components/shape-hitmemory-component.js";
import { ShapePositionComponent } from "../components/shape-position.component.js";
import { ShooterCooldownComponent } from "../components/shooter-cooldown-component.js";
import { ShootingCooldownComponent } from "../components/shooting-cooldown.component.js";
import { ShotOriginComponent } from "../components/shot-origin.component.js";
import { SoldierComponent } from "../components/soldier.component.js";
import { SparkParticlesComponent } from "../components/spark-particles.component.js";
import { SpriteComponent } from "../components/sprite.component.js";
import { TravelTimeComponent } from "../components/travel-time.component.js";
import { PlayerInitialProperties } from "../components/types/player-properties.js";
import { UIAnchorComponent } from "../components/ui-anchor.component.js";
import { UIComponent } from "../components/ui-component.js";
import { VelocityComponent } from "../components/velocity-component.js";
import { WallHitComponent } from "../components/wall-hit.component.js";
import { WeaponSpriteAttachmentComponent } from "../components/weapon-attachment.component.js";
import { WeaponAttackOriginComponent } from "../components/weapon-attack-origin.component.js";
import { WeaponMagazineComponent } from "../components/weapon-magazine.component.js";
import { WeaponComponent } from "../components/weapon.component.js";
import { ZLayerComponent } from "../components/z-layer.component.js";
import { EntityFactory } from "../entities/entity-factory.js";
import { AiAttackBehaviorSystem } from "../systems/ai-attack-behavior-system.js";
import { AiMovementBehaviorSystem } from "../systems/ai-movement-behavior-system.js";
import { AnimationSetterSystem } from "../systems/animation-setter-system.js";
import { AnimationSpriteSystem } from "../systems/animation-sprite-system.js";
import { CameraFollowSystem } from "../systems/camera-follow-system.js";
import { CollisionSystem } from "../systems/collision-system.js";
import { DamageProcessingSystem } from "../systems/damage-processing-system.js";
import { DeathProcessingSystem } from "../systems/death-processing-system.js";
// import { DynamicAttributeSystem } from "../systems/dynamic-attribute.system.js";
import { DialogSystem } from "../systems/dialog-system.js";
import { EnemyLifecicleSystem } from "../systems/enemy-lifecicle.system.js";
import { GrenadeSpawnSystem } from "../systems/grenade-spawn-system.js";
import { GrenadeUpdateSystem } from "../systems/grenade-update-system.js";
import { HitDetectionSystem } from "../systems/hit-detection-system.js";
import { InputDebugSystem } from "../systems/input-debug.system.js";
import { InputMovementSystem } from "../systems/input-movement.system.js";
import { InventoryDebugSystem } from "../systems/inventory-debug-system.js";
import { InventorySystem } from "../systems/inventory-system.js";
import { ItemDropSpawnSystem } from "../systems/item-drop-spawn.system.js";
import { ItemDropUpdateSystem } from "../systems/item-drop-update.system.js";
import { LevelProgressionSystem } from "../systems/level-progression.system.js";
import { LevelUpdateSystem } from "../systems/level-update.system.js";
import { MeleeAttackSystem } from "../systems/melee-attack.system.js";
import { MovementSystem } from "../systems/movement-system.js";
import { ParticleEmitterSystem } from "../systems/particle-emitter.system.js";
import { ProjectileSpawnSystem } from "../systems/projectile-spawn.system.js";
import { ProjectileUpdateSystem } from "../systems/projectile-update.system.js";
import { ReloadSystem } from "../systems/reload-system.js";
import { RenderSystem } from "../systems/render-system.js";
import { ShootingSystem } from "../systems/shooting-system.js";
import { TerminatorSystem } from "../systems/terminator-system.js";
import { UIUpdateSystem } from "../systems/ui-update-system.js";
import { VisibilitySystem } from "../systems/visibility-system.js";
import { WeaponSpriteAttachmenPositiontSystem } from "../systems/weapon-attachment-position-system.js";
import { WeaponSwitchSystem } from "../systems/weapon-switch-system.js";
import { SpriteLevelScalerSystem } from "../systems/zoom-level-scaler-system.js";
import { StructureBaker } from "../zones/structure-baker.js";
import { ZoneFactory } from "../zones/zone-factory.js";
import { ComponentStore } from "./component-store.js";
import { CoreManager } from "./core-manager.js";
import { DebugManager } from "./debug-manager.js";
import { EntityManager } from "./entity-manager.js";
import { FreezeManager } from "./freeze-manager.js";
import { InventoryManager } from "./inventory-manager.js";
import { LevelManager } from "./level-manager.js";
import { UIManager } from "./ui-manager.js";

export class SystemRunner {
  private renderSystem: RenderSystem;
  private visibilityManager: VisibilityManager;
  private cameraManager: CameraManager;
  private pathFindingManager: PathFindingManager = new PathFindingManager();
  private inventoryManager: InventoryManager;
  private levelManager: LevelManager;
  private freezeManager: FreezeManager;
  private uiManager: UIManager;
  private renderableComponentStore: ComponentStore<RenderableComponent> = new ComponentStore("RenderableComponent");
  private spriteComponentStore: ComponentStore<SpriteComponent> = new ComponentStore("SpriteComponent");
  private positionComponentStore: ComponentStore<PositionComponent> = new ComponentStore("PositionComponent");
  private collisionBoxComponentStore: ComponentStore<CollisionBoxComponent> = new ComponentStore("CollisionBoxComponent");
  private playerComponentStore: ComponentStore<PlayerComponent> = new ComponentStore("PlayerComponent");
  private projectileComponentStore: ComponentStore<ProjectileComponent> = new ComponentStore("ProjectileComponent");
  private velocityComponentStore: ComponentStore<VelocityComponent> = new ComponentStore("VelocityComponent");
  private intentClickComponentStore: ComponentStore<IntentClickComponent> = new ComponentStore("IntentClickComponent");
  private directionAnimComponentStore: ComponentStore<DirectionAnimComponent> = new ComponentStore("DirectionAnimComponent");
  private soldierComponentStore: ComponentStore<SoldierComponent> = new ComponentStore("SoldierComponent");
  private animationComponentStore: ComponentStore<AnimationComponent> = new ComponentStore("AnimationComponent");
  private bitmapTextComponentStore: ComponentStore<BitmapTextComponent> = new ComponentStore("BitmapTextComponent");
  private dialogComponentStore: ComponentStore<DialogComponent> = new ComponentStore("DialogComponent");
  private dialogIntentComponentStore: ComponentStore<DialogIntentComponent> = new ComponentStore("DialogIntentComponent");
  private dialogLifetimeComponentStore: ComponentStore<DialogLifetimeComponent> = new ComponentStore("DialogLifetimeComponent");
  private dialogBubbleSpriteComponentStore: ComponentStore<DialogBubbleSpriteComponent> = new ComponentStore("DialogBubbleSpriteComponent");
  private dialogAnimComponentStore: ComponentStore<DialogAnimComponent> = new ComponentStore("DialogAnimComponent");
  private shootingCooldownComponentStore: ComponentStore<ShootingCooldownComponent> = new ComponentStore("ShootingCooldownComponent");
  private enemyComponentStore: ComponentStore<EnemyComponent> = new ComponentStore("EnemyComponent");
  private intentShotComponentStore: ComponentStore<IntentShotComponent> = new ComponentStore("IntentShotComponent");
  private shooterCooldownComponentStore: ComponentStore<ShooterCooldownComponent> = new ComponentStore("ShooterCooldownComponent");
  private aiComponentStore: ComponentStore<AIComponent> = new ComponentStore("AIComponent");
  private aiMovementOrderComponentStore: ComponentStore<AIMovementOrderComponent> = new ComponentStore("AIMovementOrderComponent");
  private movementIntentComponentStore: ComponentStore<MovementIntentComponent> = new ComponentStore("MovementIntentComponent");
  private healthComponentStore: ComponentStore<HealthComponent> = new ComponentStore("HealthComponent");
  private aiAttackOrderComponentStore: ComponentStore<AIAttackOrderComponent> = new ComponentStore("AIAttackOrderComponent");
  private shotOriginComponentStore: ComponentStore<ShotOriginComponent> = new ComponentStore("ShotOriginComponent")
  private aimShootingComponent: ComponentStore<AimRotationShootingComponent> = new ComponentStore("AimRotationShootingComponent");
  private enemiesKilledComponentStore: ComponentStore<EnemiesKilledComponent> = new ComponentStore("EnemiesKilledComponent");
  private damageDealtComponentStore: ComponentStore<DamageDealtComponent> = new ComponentStore("DamageDealtComponent");
  private aiAttackRangeComponentStore: ComponentStore<AiAttackRangeComponent> = new ComponentStore("AiAttackRangeComponent");
  private aiMovementRadiusComponentStore: ComponentStore<AiMovementRadiusComponent> = new ComponentStore("AiMovementRadiusComponent");
  private enemyDeadComponentStore: ComponentStore<EnemyDeadComponent> = new ComponentStore("EnemyDeadComponent");
  private weaponSpriteAttachmentComponentStore: ComponentStore<WeaponSpriteAttachmentComponent> = new ComponentStore("WeaponSpriteAttachmentComponent");
  private zLayerComponentStore: ComponentStore<ZLayerComponent> = new ComponentStore("ZLayerComponent");
  private wallHitComponentStore: ComponentStore<WallHitComponent> = new ComponentStore("WallHitComponent");
  private offsetAppliedComponentStore: ComponentStore<OffsetAppliedComponent> = new ComponentStore("OffsetAppliedComponent");
  private directionComponentStore: ComponentStore<DirectionComponent> = new ComponentStore("Direction Component");
  private weaponComponentStore: ComponentStore<WeaponComponent> = new ComponentStore("WeaponComponent");
  private reloadIntentComponentStore: ComponentStore<ReloadIntentComponent> = new ComponentStore("ReloadIntentComponent");
  private weaponMagazineComponentStore: ComponentStore<WeaponMagazineComponent> = new ComponentStore("WeaponMagazineComponent");
  private damageTakenIntentComponentStore: ComponentStore<DamageTakenIntentComponent> = new ComponentStore("DamageTakenIntentComponent");
  private bulletFiredComponentStore: ComponentStore<BulletFiredComponent> = new ComponentStore("BulletFiredComponent");
  private grenadeComponentStore: ComponentStore<GrenadeComponent> = new ComponentStore("GrenadeComponent");
  private grenadeCooldownComponentStore: ComponentStore<GrenadeCooldownComponent> = new ComponentStore("GrenadeCooldownComponent");
  private grenadeFiredComponentStore: ComponentStore<GrenadeFiredComponent> = new ComponentStore("GrenadeFiredComponent");
  private intentGrenadeComponentStore: ComponentStore<IntentGrenadeComponent> = new ComponentStore("IntentGrenadeComponent");
  private travelTimeComponentStore: ComponentStore<TravelTimeComponent> = new ComponentStore("TravelTimeComponent");
  private fuseTimerComponentStore: ComponentStore<FuseTimerComponent> = new ComponentStore("FuseTimerComponent");
  private grenadeExplosionComponentStore: ComponentStore<GrenadeExplosionComponent> = new ComponentStore("GrenadeExplosionComponent");
  private delayedDestructionComponentStore: ComponentStore<DelayedDestructionComponent> = new ComponentStore("DelayedDestructionComponent");
  private intentMeleeComponentStore: ComponentStore<IntentMeleeComponent> = new ComponentStore("IntentMeleeComponent");
  private disableAttachmentComponentStore: ComponentStore<DisableAttachmentComponent> = new ComponentStore("DisableAttachmentComponent");
  private attackSpeedComponentStore: ComponentStore<AttackSpeedComponent> = new ComponentStore("AttackSpeedComponent");
  private disableAimComponentStore: ComponentStore<DisableAimComponent> = new ComponentStore("DisableAimComponent");
  private meleeIntentProcessedComponentStore: ComponentStore<MeleeIntentProcessedComponent> = new ComponentStore("MeleeIntentProcessedComponent")
  private initialAimAngleComponentStore: ComponentStore<InitialAimAngleComponent> = new ComponentStore("InitialAimAngleComponent");
  private shapeDimensionComponentStore: ComponentStore<ShapeDimensionComponent> = new ComponentStore("ShapeDimensionComponent");
  private shapePositionComponentStore: ComponentStore<ShapePositionComponent> = new ComponentStore("ShapePositionComponent");
  private animTimerComponentStore: ComponentStore<AnimTimerComponent> = new ComponentStore("AnimTimerComponent");
  private shapeComponentStore: ComponentStore<ShapeComponent> = new ComponentStore("ShapeComponent");
  private shapeDirectionComponentStore: ComponentStore<ShapeDirectionComponent> = new ComponentStore("ShapeDirectionComponent");
  private shapeAngleComponentStore: ComponentStore<ShapeAngleComponent> = new ComponentStore("ShapeAngleComponent");
  private shapeHitMemoryComponentStore: ComponentStore<ShapeHitMemoryComponent> = new ComponentStore("ShapeHitMemoryComponent");
  private weaponAttackOriginComponentStore: ComponentStore<WeaponAttackOriginComponent> = new ComponentStore("WeaponAttackOriginComponent");
  private dustParticlesComponentStore: ComponentStore<DustParticlesComponent> = new ComponentStore("DustParticlesComponent");
  private bloodParticlesComponentStore: ComponentStore<BloodParticlesComponent> = new ComponentStore("BloodParticlesComponent");
  private sparkParticlesComponentStore: ComponentStore<SparkParticlesComponent> = new ComponentStore("SparkParticlesComponent");
  private cameraComponentStore: ComponentStore<CameraComponent> = new ComponentStore("CameraComponent");
  private hitBoxComponentStore: ComponentStore<HitBoxComponent> = new ComponentStore("HitBoxComponent");
  private deathIntentComponentStore: ComponentStore<DeathIntentComponent> = new ComponentStore("DeathIntentComponent");
  private inventoryComponentStore: ComponentStore<InventoryComponent> = new ComponentStore("InventoryComponent");
  private itemBoxComponentStore: ComponentStore<ItemBoxComponent> = new ComponentStore("ItemBoxComponent");
  private awaitingAnimationEndComponentStore: ComponentStore<AwaitingAnimationEndComponent> = new ComponentStore("AwaitingAnimationEndComponent");
  private itemDropIntentComponentStore: ComponentStore<ItemDropIntentComponent> = new ComponentStore("ItemDropIntentComponent");
  private itemDroppedComponentStore: ComponentStore<ItemDroppedComponent> = new ComponentStore("ItemDroppedComponent");
  private screenPositionComponentStore: ComponentStore<ScreenPositionComponent> = new ComponentStore("ScreenPositionComponent");
  private uiAnchorComponentStore: ComponentStore<UIAnchorComponent> = new ComponentStore("UIAnchorComponent");
  private uiComponentStore: ComponentStore<UIComponent> = new ComponentStore("UIComponent");
  private animationSpriteSystem: AnimationSpriteSystem;
  private inputDebugSystem: InputDebugSystem;
  private inputMovementSystem: InputMovementSystem;
  private shootingSystem: ShootingSystem;
  private projectileSpawnSystem: ProjectileSpawnSystem;
  private grenadeSpawnSystem: GrenadeSpawnSystem;
  private collisionSystem: CollisionSystem;
  private movementSystem: MovementSystem;
  private animationSetterSystem: AnimationSetterSystem;
  private terminatorSystem: TerminatorSystem;
  private projectileUpdateSystem: ProjectileUpdateSystem;
  private grenadeUpdateSystem: GrenadeUpdateSystem;
  private aiMovementBehaviorSystem: AiMovementBehaviorSystem;
  private aiAttackBehaviorSystem: AiAttackBehaviorSystem;
  private levelProgressionSystem: LevelProgressionSystem;
  private enemyLifecicleSystem: EnemyLifecicleSystem;
  private weaponSpriteAttachmentSystem: WeaponSpriteAttachmenPositiontSystem;
  private entityFactory: EntityFactory;
  private playerInitialProperties: PlayerInitialProperties;
  private spriteLevelScaler: SpriteLevelScalerSystem;
  private levelUpdateSystem: LevelUpdateSystem;
  // private dynamicAttributeSystem: DynamicAttributeSystem;
  private reloadSystem: ReloadSystem;
  private meleeAttackSystem: MeleeAttackSystem;
  private particleEmitterSystem: ParticleEmitterSystem;
  private cameraFollowSystem: CameraFollowSystem;
  private visibilitySystem: VisibilitySystem;
  private zoneFactory: ZoneFactory;
  private structureBaker: StructureBaker;
  private dialogSystem: DialogSystem;
  private hitDetectionSystem: HitDetectionSystem;
  private damageProcessingSystem: DamageProcessingSystem;
  private deathProcessingSystem: DeathProcessingSystem;
  private inventorySystem: InventorySystem;
  private inventoryDebugSystem: InventoryDebugSystem;
  private itemDropSpawnSystem: ItemDropSpawnSystem;
  private itemDropUpdateSystem: ItemDropUpdateSystem;
  private uiUpdateSystem: UIUpdateSystem;
  private weaponSwitchSystem: WeaponSwitchSystem;

  constructor(
    private worldTilemapManager: WorldTilemapManager,
    private spriteManager: SpriteManager,
    private textManager: TextManager,
    private entityManager: EntityManager,
    private soundManager: SoundManager,
    private rendererEngine: RendererEngine,
    private debugManager: DebugManager,
  ) {

    this.cameraManager = new CameraManager(this.worldTilemapManager);
    this.visibilityManager = new VisibilityManager();
    this.freezeManager = new FreezeManager();
    this.inventoryManager = new InventoryManager();
    this.playerInitialProperties = new PlayerInitialProperties();
    this.structureBaker = new StructureBaker();
    this.zoneFactory = new ZoneFactory(this.structureBaker)
    this.uiManager = new UIManager(this.cameraManager);
    this.entityFactory = new EntityFactory(entityManager, this.inventoryManager, this.uiManager, this.renderableComponentStore, this.playerComponentStore, this.enemyComponentStore, this.positionComponentStore, this.spriteComponentStore, this.projectileComponentStore, this.shooterCooldownComponentStore, this.velocityComponentStore, this.movementIntentComponentStore, this.animationComponentStore, this.directionAnimComponentStore, this.collisionBoxComponentStore, this.aiComponentStore, this.healthComponentStore, this.shotOriginComponentStore, this.damageDealtComponentStore, this.shootingCooldownComponentStore, this.aiAttackRangeComponentStore, this.aiMovementRadiusComponentStore, this.enemyDeadComponentStore, this.aimShootingComponent, this.weaponSpriteAttachmentComponentStore, this.zLayerComponentStore, this.directionComponentStore, this.weaponComponentStore, this.weaponMagazineComponentStore, this.grenadeComponentStore, this.travelTimeComponentStore, this.fuseTimerComponentStore, this.shapeDimensionComponentStore, this.shapePositionComponentStore, this.shapeComponentStore, this.shapeDirectionComponentStore, this.shapeAngleComponentStore, this.shapeHitMemoryComponentStore, this.cameraComponentStore, this.hitBoxComponentStore, this.dialogComponentStore, this.dialogLifetimeComponentStore, this.dialogBubbleSpriteComponentStore, this.bitmapTextComponentStore, this.dialogAnimComponentStore, this.inventoryComponentStore, this.itemBoxComponentStore, this.itemDroppedComponentStore, this.screenPositionComponentStore, this.uiAnchorComponentStore, this.uiComponentStore);
    this.enemyLifecicleSystem = new EnemyLifecicleSystem(this.positionComponentStore, this.playerComponentStore, this.enemyComponentStore, this.enemyDeadComponentStore, this.entityFactory, this.worldTilemapManager, this.spriteManager, this.soundManager, this.freezeManager, this.spriteComponentStore, this.worldTilemapManager);
    this.levelManager = new LevelManager(this.enemyLifecicleSystem, this.worldTilemapManager, this.cameraManager, this.zoneFactory, this.entityFactory, this.playerComponentStore, this.positionComponentStore, this.movementIntentComponentStore, this.playerInitialProperties, this.uiManager);
    // this.dynamicAttributeSystem = new DynamicAttributeSystem(this.levelManager, this.entityFactory, this.velocityComponentStore, this.projectileComponentStore, this.playerComponentStore, this.enemyComponentStore, this.damageTakenIntentComponentStore, this.healthComponentStore, this.damageDealtComponentStore, this.enemiesKilledComponentStore, this.weaponMagazineComponentStore, this.reloadIntentComponentStore, this.bulletFiredComponentStore, this.grenadeBeltComponentStore, this.grenadeFiredComponentStore, this.enemyDeadComponentStore);
    this.levelUpdateSystem = new LevelUpdateSystem(this.levelManager);
    this.inputDebugSystem = new InputDebugSystem(this.debugManager, this.cameraManager);
    this.inventoryDebugSystem = new InventoryDebugSystem(this.inventoryManager, this.inventoryComponentStore, this.playerComponentStore, this.healthComponentStore);
    this.inputMovementSystem = new InputMovementSystem(this.positionComponentStore, this.movementIntentComponentStore, this.playerComponentStore, this.velocityComponentStore)
    this.shootingSystem = new ShootingSystem(this.playerComponentStore, this.intentShotComponentStore, this.positionComponentStore, this.aimShootingComponent, this.weaponSpriteAttachmentComponentStore, this.intentGrenadeComponentStore, this.weaponComponentStore, this.intentMeleeComponentStore, this.disableAimComponentStore, this.inventoryComponentStore, this.reloadIntentComponentStore, this.shootingCooldownComponentStore, this.cameraManager, this.debugManager, this.inventoryManager)
    this.projectileSpawnSystem = new ProjectileSpawnSystem(this.spriteManager, this.soundManager, this.positionComponentStore, this.weaponSpriteAttachmentComponentStore, this.entityFactory, this.intentShotComponentStore, this.shootingCooldownComponentStore, this.bulletFiredComponentStore, this.damageDealtComponentStore, this.playerComponentStore, this.enemyComponentStore);
    this.projectileUpdateSystem = new ProjectileUpdateSystem(this.positionComponentStore, this.projectileComponentStore, this.velocityComponentStore, this.movementIntentComponentStore, this.directionComponentStore);
    this.collisionSystem = new CollisionSystem(this.spriteComponentStore, this.positionComponentStore, this.collisionBoxComponentStore, this.movementIntentComponentStore, this.projectileComponentStore, this.grenadeComponentStore, this.velocityComponentStore, this.shotOriginComponentStore, this.playerComponentStore, this.enemyComponentStore, this.spriteManager, this.worldTilemapManager, this.entityFactory);
    this.renderSystem = new RenderSystem(this.renderableComponentStore, this.positionComponentStore, this.screenPositionComponentStore, this.spriteComponentStore, this.cameraManager, this.worldTilemapManager, this.rendererEngine, this.spriteManager, this.directionAnimComponentStore, this.aimShootingComponent, this.zLayerComponentStore, this.visibilityManager, this.debugManager, this.dialogBubbleSpriteComponentStore, this.bitmapTextComponentStore, this.textManager);
    this.inputMovementSystem = new InputMovementSystem(this.positionComponentStore, this.movementIntentComponentStore, this.playerComponentStore, this.velocityComponentStore)
    this.grenadeSpawnSystem = new GrenadeSpawnSystem(this.positionComponentStore, this.weaponSpriteAttachmentComponentStore, this.entityFactory, this.shooterCooldownComponentStore, this.playerComponentStore, this.grenadeCooldownComponentStore, this.grenadeFiredComponentStore, this.intentGrenadeComponentStore);
    this.projectileUpdateSystem = new ProjectileUpdateSystem(this.positionComponentStore, this.projectileComponentStore, this.velocityComponentStore, this.movementIntentComponentStore, this.directionComponentStore);
    this.grenadeUpdateSystem = new GrenadeUpdateSystem(this.entityFactory, this.positionComponentStore, this.grenadeComponentStore, this.velocityComponentStore, this.movementIntentComponentStore, this.directionComponentStore, this.travelTimeComponentStore, this.fuseTimerComponentStore, this.shotOriginComponentStore, this.playerComponentStore, this.enemyComponentStore, this.damageTakenIntentComponentStore, this.grenadeExplosionComponentStore, this.delayedDestructionComponentStore, this.animationComponentStore, this.enemyDeadComponentStore);
    this.collisionSystem = new CollisionSystem(this.spriteComponentStore, this.positionComponentStore, this.collisionBoxComponentStore, this.movementIntentComponentStore, this.projectileComponentStore, this.grenadeComponentStore, this.velocityComponentStore, this.shotOriginComponentStore, this.playerComponentStore, this.enemyComponentStore, this.spriteManager, this.worldTilemapManager, this.entityFactory);
    this.hitDetectionSystem = new HitDetectionSystem(this.spriteManager, this.entityFactory, this.hitBoxComponentStore, this.movementIntentComponentStore, this.positionComponentStore, this.spriteComponentStore, this.projectileComponentStore, this.grenadeComponentStore, this.shotOriginComponentStore, this.playerComponentStore, this.enemyComponentStore, this.damageTakenIntentComponentStore, this.itemBoxComponentStore);
    this.damageProcessingSystem = new DamageProcessingSystem(this.damageTakenIntentComponentStore, this.healthComponentStore, this.deathIntentComponentStore);
    this.deathProcessingSystem = new DeathProcessingSystem(this.levelManager, this.entityFactory, this.deathIntentComponentStore, this.playerComponentStore, this.enemyComponentStore, this.enemyDeadComponentStore, this.itemBoxComponentStore, this.awaitingAnimationEndComponentStore, this.itemDropIntentComponentStore, this.positionComponentStore)
    this.movementSystem = new MovementSystem(this.positionComponentStore, this.movementIntentComponentStore, this.playerComponentStore, this.shooterCooldownComponentStore);
    this.animationSetterSystem = new AnimationSetterSystem(this.spriteManager, this.movementIntentComponentStore, this.positionComponentStore, this.directionAnimComponentStore, this.animationComponentStore, this.aiComponentStore, this.playerComponentStore, this.aimShootingComponent, this.weaponSpriteAttachmentComponentStore, this.wallHitComponentStore, this.projectileComponentStore, this.spriteComponentStore, this.offsetAppliedComponentStore, this.grenadeComponentStore, this.grenadeExplosionComponentStore, this.itemBoxComponentStore, this.awaitingAnimationEndComponentStore);
    this.terminatorSystem = new TerminatorSystem(this.entityFactory, this.intentClickComponentStore, this.movementIntentComponentStore, this.shootingCooldownComponentStore, this.intentShotComponentStore, this.wallHitComponentStore, this.grenadeCooldownComponentStore, this.intentGrenadeComponentStore, this.intentMeleeComponentStore, this.meleeIntentProcessedComponentStore, this.enemyDeadComponentStore, this.shapeComponentStore, this.projectileComponentStore);
    this.animationSpriteSystem = new AnimationSpriteSystem(this.animationComponentStore, this.spriteComponentStore, this.awaitingAnimationEndComponentStore);
    this.aiMovementBehaviorSystem = new AiMovementBehaviorSystem(this.positionComponentStore, this.velocityComponentStore, this.movementIntentComponentStore, this.aiComponentStore, this.aiMovementOrderComponentStore, this.playerComponentStore, this.pathFindingManager);
    this.aiAttackBehaviorSystem = new AiAttackBehaviorSystem(this.positionComponentStore, this.intentShotComponentStore, this.aiComponentStore, this.aiAttackOrderComponentStore, this.playerComponentStore, this.aimShootingComponent, this.weaponSpriteAttachmentComponentStore, this.spriteComponentStore, this.enemyComponentStore, this.intentGrenadeComponentStore, this.intentMeleeComponentStore, this.disableAimComponentStore, this.weaponComponentStore);
    this.spriteLevelScaler = new SpriteLevelScalerSystem(this.spriteComponentStore, this.spriteManager, this.levelManager, this.worldTilemapManager, this.renderableComponentStore);
    this.weaponSpriteAttachmentSystem = new WeaponSpriteAttachmenPositiontSystem(this.positionComponentStore, this.weaponSpriteAttachmentComponentStore, this.zLayerComponentStore, this.spriteComponentStore, this.aimShootingComponent, this.disableAttachmentComponentStore);
    this.levelProgressionSystem = new LevelProgressionSystem(this.enemiesKilledComponentStore, this.levelManager);
    this.reloadSystem = new ReloadSystem(this.soundManager, this.inventoryManager, this.reloadIntentComponentStore, this.playerComponentStore, this.inventoryComponentStore)
    this.meleeAttackSystem = new MeleeAttackSystem(this.intentMeleeComponentStore, this.weaponSpriteAttachmentComponentStore, this.weaponComponentStore, this.positionComponentStore, this.aimShootingComponent, this.shooterCooldownComponentStore, this.playerComponentStore, this.enemyComponentStore, this.attackSpeedComponentStore, this.spriteComponentStore, this.disableAimComponentStore, this.meleeIntentProcessedComponentStore, this.initialAimAngleComponentStore, this.entityFactory, this.shapeComponentStore, this.disableAttachmentComponentStore, this.weaponAttackOriginComponentStore);
    this.particleEmitterSystem = new ParticleEmitterSystem(this.rendererEngine, this.bloodParticlesComponentStore, this.dustParticlesComponentStore, this.sparkParticlesComponentStore);
    this.cameraFollowSystem = new CameraFollowSystem(this.cameraComponentStore, this.positionComponentStore, this.cameraManager);
    this.dialogSystem = new DialogSystem(this.entityFactory, this.dialogIntentComponentStore, this.dialogComponentStore, this.dialogLifetimeComponentStore, this.dialogAnimComponentStore, this.bitmapTextComponentStore, this.animationComponentStore, this.playerComponentStore, this.positionComponentStore, this.spriteComponentStore);
    this.visibilitySystem = new VisibilitySystem(this.playerComponentStore, this.positionComponentStore, this.worldTilemapManager, this.visibilityManager);
    this.inventorySystem = new InventorySystem(this.inventoryManager, this.inventoryComponentStore, this.playerComponentStore, this.bulletFiredComponentStore, this.grenadeFiredComponentStore);
    this.itemDropSpawnSystem = new ItemDropSpawnSystem(this.entityFactory, this.itemDropIntentComponentStore);
    this.itemDropUpdateSystem = new ItemDropUpdateSystem(this.entityFactory, this.spriteManager, this.inventoryManager, this.itemDroppedComponentStore, this.positionComponentStore, this.playerComponentStore, this.spriteComponentStore, this.inventoryComponentStore);
    this.uiUpdateSystem = new UIUpdateSystem(this.entityFactory, this.inventoryManager, this.playerInitialProperties, this.uiComponentStore, this.inventoryComponentStore, this.playerComponentStore, this.healthComponentStore, this.spriteComponentStore, this.bitmapTextComponentStore, this.screenPositionComponentStore);
    this.weaponSwitchSystem = new WeaponSwitchSystem(this.inventoryManager, this.entityFactory, this.inventoryComponentStore, this.playerComponentStore);
  }

  update() {
    if (!this.freezeManager.gameFrozen) {
      this.inputDebugSystem.update(CoreManager.timeSinceLastRender);
      this.inventoryDebugSystem.update(CoreManager.timeSinceLastRender);
      this.cameraFollowSystem.update();
      this.levelProgressionSystem.update(CoreManager.timeSinceLastRender);
      this.spriteLevelScaler.update(CoreManager.timeSinceLastRender);
      this.enemyLifecicleSystem.update(CoreManager.timeSinceLastRender);
      //this.dynamicAttributeSystem.update(CoreManager.timeSinceLastRender);
      this.reloadSystem.update(CoreManager.timeSinceLastRender);
      this.inputMovementSystem.update(CoreManager.timeSinceLastRender);
      this.weaponSwitchSystem.update(CoreManager.timeSinceLastRender);
      this.aiMovementBehaviorSystem.update(CoreManager.timeSinceLastRender);
      this.aiAttackBehaviorSystem.update(CoreManager.timeSinceLastRender)
      this.shootingSystem.update(CoreManager.timeSinceLastRender);
      //this.meleeAttackSystem.update(CoreManager.timeSinceLastRender);
      this.projectileSpawnSystem.update(CoreManager.timeSinceLastRender);
      this.grenadeSpawnSystem.update(CoreManager.timeSinceLastRender);
      this.projectileUpdateSystem.update(CoreManager.timeSinceLastRender);
      this.itemDropSpawnSystem.update(CoreManager.timeSinceLastRender);
      this.itemDropUpdateSystem.update(CoreManager.timeSinceLastRender);
      this.grenadeUpdateSystem.update(CoreManager.timeSinceLastRender);
      this.animationSetterSystem.update(CoreManager.timeSinceLastRender);
      this.animationSpriteSystem.update(CoreManager.timeSinceLastRender);
      this.collisionSystem.update(CoreManager.timeSinceLastRender);
      this.hitDetectionSystem.update(CoreManager.timeSinceLastRender);
      this.damageProcessingSystem.update(CoreManager.timeSinceLastRender);
      this.deathProcessingSystem.update(CoreManager.timeSinceLastRender);
      this.movementSystem.update(CoreManager.timeSinceLastRender);
      this.weaponSpriteAttachmentSystem.update(CoreManager.timeSinceLastRender);
      this.dialogSystem.update(CoreManager.timeSinceLastRender);
      this.visibilitySystem.update(CoreManager.timeSinceLastRender);
      this.inventorySystem.update(CoreManager.timeSinceLastRender);
      this.particleEmitterSystem.update(CoreManager.timeSinceLastRender);
      this.spriteLevelScaler.update(CoreManager.timeSinceLastRender);
      this.uiUpdateSystem.update(CoreManager.timeSinceLastRender);
      this.renderSystem.update(CoreManager.timeSinceLastRender);
      this.terminatorSystem.update(CoreManager.timeSinceLastRender);
      this.levelUpdateSystem.update();
    }
  }

  initialize() {
    this.levelManager.update();
  }
}
