export enum SpriteSheetName {
  TERRAIN = "terrain",
  PLAYER = "player",
  ENEMY = "enemy",
  PROJECTILE = "projectile",
  WEAPON = "weapon",
  DIALOG_BALLOON = "dialog_balloon",
  BULLET_WALL_HIT = "bullet_wall_hit",
  GRENADE_EXPLOSION = "grenade_explosion",
  BLANK = "blank",
  GRENADE_DROP = "grenade_drop",
  PISTOL_MAG_DROP = "pistol_mag_drop",
  SMG_MAG_DROP = "smg_mag_drop",
  WOODEN_BOX = "wooden_box",
  HEALTH_BAR = "health_bar",
  RESOURCES_ICON = "resources",
  KEYBOARD_KEY = "keyboard_key",
  WEAPON_FRAME = "weapon_frame",
  MELEE_ATTACK = "melee_attack",
}
