export enum MiscResourceType {
    Calculator = "calculator",
    CarBattery = "car_battery",
    CassetteTape = "cassette_tape",
    CityMap = "city_map",
    CleaningSponge = "cleaning_sponge",
    CopperWire = "copper_wire",
    DuctTape = "duct_tape",
    ElectricCoil = "electric_coil",
    ElectricalTape = "electrical_tape",
    EmptySodaCan = "empty_soda_can",
    ExtensionCord = "extension_cord",
    FanControl = "fan_control",
    FieldDressing = "field_dressing",
    Fuse = "fuse",
    GasHose = "gas_hose",
    Hanger = "hanger",
    Hinge = "hinge",
    HygieneKit = "hygiene_kit",
    KitchenTimer = "kitchen_timer",
    LightBulbPack = "light_bulb_pack",
    Lighter = "lighter",
    LooseBatteries = "loose_batteries",
    LargeBackpack = "large_backpack",
    MattressSprings = "mattress_springs",
    MediumBackpack = "medium_backpack",
    MetalPipe = "metal_pipe",
    MetalSheet = "metal_sheet",
    NailBox = "nail_box",
    Notebook = "notebook",
    OilFilter = "oil_filter",
    OldShowerhead = "old_showerhead",
    PackOfCigarettes = "pack_of_cigarettes",
    PlasticZipTie = "plastic_zip_tie",
    PressureValve = "pressure_valve",
    PriceTagRoll = "price_tag_roll",
    Radio = "radio",
    RemoteControl = "remote_control",
    Screws = "screws",
    Screwdriver = "screwdriver",
    SewingKit = "sewing_kit",
    SmallBackpack = "small_backpack",
    SmallMotor = "small_motor",
    SteelBrush = "steel_brush",
    SteelCable = "steel_cable",
    SteelSponge = "steel_sponge",
    SuperGlue = "super_glue",
    WireRoll = "wire_roll",
    Wristwatch = "wristwatch",
}

export const MISC_RESOURCE_TYPES: readonly MiscResourceType[] = [
    MiscResourceType.Calculator,
    MiscResourceType.CarBattery,
    MiscResourceType.CassetteTape,
    MiscResourceType.CityMap,
    MiscResourceType.CleaningSponge,
    MiscResourceType.CopperWire,
    MiscResourceType.DuctTape,
    MiscResourceType.ElectricCoil,
    MiscResourceType.ElectricalTape,
    MiscResourceType.EmptySodaCan,
    MiscResourceType.ExtensionCord,
    MiscResourceType.FanControl,
    MiscResourceType.FieldDressing,
    MiscResourceType.Fuse,
    MiscResourceType.GasHose,
    MiscResourceType.Hanger,
    MiscResourceType.Hinge,
    MiscResourceType.HygieneKit,
    MiscResourceType.KitchenTimer,
    MiscResourceType.LightBulbPack,
    MiscResourceType.Lighter,
    MiscResourceType.LooseBatteries,
    MiscResourceType.LargeBackpack,
    MiscResourceType.MattressSprings,
    MiscResourceType.MediumBackpack,
    MiscResourceType.MetalPipe,
    MiscResourceType.MetalSheet,
    MiscResourceType.NailBox,
    MiscResourceType.Notebook,
    MiscResourceType.OilFilter,
    MiscResourceType.OldShowerhead,
    MiscResourceType.PackOfCigarettes,
    MiscResourceType.PlasticZipTie,
    MiscResourceType.PressureValve,
    MiscResourceType.PriceTagRoll,
    MiscResourceType.Radio,
    MiscResourceType.RemoteControl,
    MiscResourceType.Screws,
    MiscResourceType.Screwdriver,
    MiscResourceType.SewingKit,
    MiscResourceType.SmallBackpack,
    MiscResourceType.SmallMotor,
    MiscResourceType.SteelBrush,
    MiscResourceType.SteelCable,
    MiscResourceType.SteelSponge,
    MiscResourceType.SuperGlue,
    MiscResourceType.WireRoll,
    MiscResourceType.Wristwatch,
];
export const MAX_MISC_RESOURCE_AMOUNT = 99;

export function isMiscResourceType(value: unknown): value is MiscResourceType {
    return typeof value === "string"
        && MISC_RESOURCE_TYPES.indexOf(value as MiscResourceType) !== -1;
}

export function clampMiscResourceAmount(amount: number): number {
    return Math.max(0, Math.min(amount, MAX_MISC_RESOURCE_AMOUNT));
}
